name = "lastframe-getter"
main = "src/worker.ts"
compatibility_date = "2025-09-09"

[assets]
directory = "dist/client"
binding = "ASSETS"
not_found_handling = "single-page-application"
workers_dev = true

[vars]
NODE_ENV = "production"
